version: "3.7"

networks:
  wavdio-net:

services:

  wavdio-angular:
    container_name: wavdio-angular
    build: .
    networks:
      - wavdio-net
    ports:
      - "80:80"
    depends_on:
      - wavdio-express

  wavdio-express:
    container_name: wavdio-express
    image: xvlcw/wavdio-express:2
    command: node ./bin/server.js --db-uri mongodb://wavdio-mongo:27017/
    networks:
      - wavdio-net
    depends_on:
      - wavdio-mongo

  wavdio-mongo:
    container_name: wavdio-mongo
    image: mongo:5-focal
    networks:
      - wavdio-net
    expose:
      - 27017
